# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45d7eed078a1d9472a55f32e659561ffba383c2339b390734ad7460663b6fad43e6aa1a3603f935de003428414f46816ba0b2855b062c61a07c16f939b6b58cf

test:
  secret_key_base: 0bdf7a361f3b4e0855ec6bf0745a9c122d0aafd50c6a7111e19c0e5283cc1fab48234a514e6fe82e0329bdfc4f269b99a3bf23bbef538eeb5833967cc0f5833f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
